import random
# Write a function that accepts a user's choice of game mode (1 or 2) and returns the selected mode. The function should be called getGameMode()
from src.GameUI import (
    guess,
    print_color_code_error,
    print_color_code_length_error,
)

# Write a function called generateCode() that generates a random code consisting of 4 colors. The colors should be selected from the following list: ["green", "red", "yellow", "blue", "white", "black"]. The function should return the generated code as a list of colors.
def generateCode():
    colors = ["green", "red", "yellow", "blue", "white", "black"]
    code = [random.choice(colors) for _ in range(4)]
    return code

valid_colors = ["green", "red", "yellow", "blue", "white", "black"]
#replace print statements in the validate_color_code function with return statements that return False if the code is invalid and True if the code is valid. The function should still print error messages for invalid input, but it should not print anything for valid input.
def validate_color_code(code, valid_colors):
    """
    Validates that the code contains exactly 4 valid colors.
    
    Args:
        code (str): The user's color code input
        valid_colors (list): List of valid color names
        
    Returns:
        bool: True if code is valid, False otherwise
    """
    colors = code.strip().split(',')
    
    if len(colors) != 4:
        print_color_code_length_error(len(colors))
        return False
    
    for color in colors:
        color = color.strip().lower()
        if color not in [c.lower() for c in valid_colors]:
            print_color_code_error(color, valid_colors)
            return False
    
    return True


def compareGuess(user_guess, generated_code):
    """
    Compares the user's guess to the generated code and counts correct positions and colors.
    
    Args:
        user_guess (list): The user's guessed colors        generated_code (list): The secret code generated by the computer
    Returns:
        tuple: (correct_position, correct_color_wrong_position)
    """
    # The game collects guesses as a comma-separated string (e.g. "red, green, blue, yellow").
    # Normalize into lists so this function works whether it receives a string or a list.
    if isinstance(user_guess, str):
        user_guess = [c.strip().lower() for c in user_guess.split(',') if c.strip()]
    else:
        user_guess = [str(c).strip().lower() for c in user_guess]

    if isinstance(generated_code, str):
        generated_code = [c.strip().lower() for c in generated_code.split(',') if c.strip()]
    else:
        generated_code = [str(c).strip().lower() for c in generated_code]

    correct_position = sum(1 for g, c in zip(user_guess, generated_code) if g == c)
    
    # Count colors in the wrong position
    code_color_counts = {}
    guess_color_counts = {}
    
    for color in generated_code:
        code_color_counts[color] = code_color_counts.get(color, 0) + 1
        
    for color in user_guess:
        guess_color_counts[color] = guess_color_counts.get(color, 0) + 1
        
    correct_color_wrong_position = sum(min(code_color_counts.get(color, 0), guess_color_counts.get(color, 0)) for color in guess_color_counts) - correct_position
    return correct_position, correct_color_wrong_position


#write a function called guessAlgorithm that takes the bot's previous guesses, the user's feedback for each guess, and the current guess count as arguments. On its first guess, it should guess two colours twice (e.g. "white, white, black, black"). For subsequent guesses, it should guess codes that minimize the search space. The function should return the bot's next guess as a list of colors
def guessAlgorithm(previous_guess, feedback, guess_count):
    colors = ["green", "red", "yellow", "blue", "white", "black"]
    
    # For the first guess, return a guess of two random colors repeated twice
    if guess_count == 0:
        two_colors = random.sample(colors, 2)
        first_guess = [two_colors[0], two_colors[0], two_colors[1], two_colors[1]]
        return first_guess

    # Build the full set of possible 4-color codes
    from itertools import product
    all_possible = [list(p) for p in product(colors, repeat=4)]

    # Filter to only codes consistent with all previous guesses and feedback
    remaining = []
    for candidate in all_possible:
        consistent = True
        for prev_guess, (exact, partial) in zip(previous_guess, feedback):
            e, p = compareGuess(prev_guess, candidate)
            if e != exact or p != partial:
                consistent = False
                break
        if consistent:
            remaining.append(candidate)

    if not remaining:
        return random.choices(colors, k=4)

    # Minimax: pick the guess that minimises the worst-case number of remaining candidates
    best_guess = None
    best_score = float('inf')

    # To keep it fast, only score candidates that are still possible answers first,
    # then fall back to all codes if nothing reduces the space enough
    candidates_to_score = all_possible

    for candidate in candidates_to_score:
        # Partition remaining codes by the feedback this candidate would produce
        partition = {}
        for possibility in remaining:
            fb = compareGuess(candidate, possibility)
            partition[fb] = partition.get(fb, 0) + 1
        worst_case = max(partition.values())
        # Prefer guesses that are still possible answers (tiebreak)
        is_possible = candidate in remaining
        score = (worst_case, not is_possible)
        if score < (best_score, True):
            best_guess = candidate
            best_score = worst_case

    return best_guess
# ...existing code...

def cheaterCheck(user_feedback, bot_guess, secret_code):
    """Checks whether the user's feedback is consistent with the guess and secret.

    Returns:
        str | None: A cheating message when feedback is inconsistent, otherwise None.
    """
    expected_feedback = compareGuess(bot_guess, secret_code)
    if user_feedback != expected_feedback:
        return "Cheating detected: feedback does not match expected results."
    return None


